name: Terraform pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  plan:
    name: Terraform Setup, Initialize & Validate
    runs-on: ubuntu-latest

    env:
      TF_VERSION: "1.13.3"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: ${{ env.TF_VERSION }}

      - name: TF Initialize, Format, Validate & Plan
        run: |
          terraform init
          terraform fmt -recursive

      - name: TF Validate
        run: |
          terraform validate
      
      